### ISSUE TITLE
Error on connection

### ISSUE THREAD

**Issue by JuanjoRomero** [yagasoft/DynamicsCrm-CodeGenerator#14]
When I try to connect this error appears.

 Exception: System.MissingMethodException
- Message: Method not found: 'Microsoft.Xrm.Sdk.Client.OrganizationServiceProxy Microsoft.Xrm.Tooling.Connector.CrmServiceClient.get_OrganizationServiceProxy()'.
- Source: Yagasoft.Libraries.EnhancedOrgService
- Target site: System.Nullable`1[System.Boolean] EnsureTokenValid(Microsoft.Xrm.Sdk.IOrganizationService, Int32)
- HResult: -2146233069
- Stack trace:
   at Yagasoft.Libraries.EnhancedOrgService.Helpers.ConnectionHelpers.EnsureTokenValid(IOrganizationService crmService, Int32 tokenExpiryCheckSecs)
   at Yagasoft.Libraries.EnhancedOrgService.Pools.ServicePool`1.GetService()
   at Yagasoft.Libraries.EnhancedOrgService.Services.Enhanced.EnhancedOrgServiceBase.GetService()
   at Yagasoft.Libraries.EnhancedOrgService.Services.Enhanced.EnhancedOrgServiceBase.TryRunOperation[TResult](Func`2 action, Operation operation, ExecuteParams executeParams, Boolean isDelegated)
   at Yagasoft.Libraries.EnhancedOrgService.Services.Enhanced.EnhancedOrgServiceBase.ExecuteAsOperation(OrganizationRequest request, ExecuteParams executeParams, Func`3 undoFunction)
   at Yagasoft.Libraries.EnhancedOrgService.Services.Enhanced.EnhancedOrgServiceBase.Execute(OrganizationRequest request, ExecuteParams executeParams, Func`3 undoFunction)
   at Yagasoft.Libraries.EnhancedOrgService.Services.Enhanced.EnhancedOrgServiceBase.Execute(OrganizationRequest request)
   at Yagasoft.CrmCodeGenerator.Helpers.MetadataHelpers.RefreshSettingsEntityMetadata(Settings settings, IConnectionManager connectionManager, MetadataCache metadataCache)
   at CrmCodeGenerator.VSPackage.Dialogs.EntitySelection.RefreshEntityMetadata()
   at CrmCodeGenerator.VSPackage.Dialogs.EntitySelection.<Window_Loaded>b__45_0()

**Comment by yagasoft** [comment]
Hello, @JuanjoRomero ,
Do you have any extensions related to Dynamics installed in Visual Studio?

**Comment by yagasoft** [comment]
@JuanjoRomero 
This issue is most probably caused by another extension installed in VS that uses an older version of the SDK. That older version might be missing a method that this one needs.
